#!/usr/bin/python
# -*- coding: utf-8 -*-
from signal import signal, alarm, SIGALRM
from subprocess import Popen,PIPE
from sys import stdin as SysStdin
from time import strftime
from os import system

from config_mod import replace_p,TEXT_COLOR,BACKGROUND_COLOR,FONT,TIME_COLOR, TIME_BACKGROUND_COLOR, SCREEN_PERCENTAGE 
import mpd_mod
import weather
import cpu
import ram
import hddtemp
import battery
from colors import *
NEW_LINE=""
res_proc= Popen("xrandr  | grep \* | cut -d' ' -f4",shell=True,stdout=PIPE)
resolution = res_proc.stdout
[SCREEN_WIDTH,SCREEN_HEIGHT]=resolution.read().split()[0].split('x')
print SCREEN_WIDTH+'x'+SCREEN_HEIGHT
"""METHODS AND FUNCTIONS USED"""
def get_data():
  if len(p)>160:
    NEW_LINE="\n"
  else:
    NEW_LINE="" 
  return "^tw()" + replace_p(p) + SPACE_PR_SYS_DATA + cpu.CPU + ram.RAM + hddtemp.HDDTEMP + battery.BATTERY + NOW()+NEW_LINE+weather.WEATHER_COND+mpd_mod.SONG+SPACE_AP_TIME
##+get_top_processes()
def NOW():
  return " "+set_colors(TIME_COLOR,TIME_BACKGROUND_COLOR)+strftime("%d-%m %H:%M")+set_normal_color()
def handler(signum,frame):
  return

"""INNER SPACES"""

SPACE_PR_SYS_DATA=" |"
SPACE_AP_TIME="\n"

"""LAUNCH DZEN"""

proc = Popen('dzen2 -w '+str(int(SCREEN_WIDTH)*float(SCREEN_PERCENTAGE))+' -fg '+TEXT_COLOR+' -bg '+BACKGROUND_COLOR+' -ta l -l 1 -fn '+FONT, 
                        shell=True, 
                        stdin=PIPE
                        )
(child_stdin, child_stdout) = (proc.stdin, proc.stdout)
signal(SIGALRM,handler)


"""MAIN LOOP"""
weather.get_weather().start()
hddtemp.get_hddtemp().start()
cpu.get_cpu().start()
ram.get_mem().start()
battery.get_battery().start()
mpd_mod.get_mpd().start()
while True:
  alarm(1)
  try:
    p=SysStdin.readline()
    p=p.replace('\n','')
    data=get_data()
    child_stdin.write(data)
    continue
  except:
    data=get_data()
    child_stdin.write(data)
    continue
